name: Build iOS App

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter doctor -v

      - name: Get Packages
        run: flutter pub get

      - name: Build IPA (Debug)
        run: flutter build ipa --debug --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: App-Debug-IPA
          path: build/ios/ipa/*.ipa
