name: Build iOS App

on:
  workflow_dispatch:  # لتشغيله يدوياً

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # غيري إذا كنت تستخدمين إصداراً آخر

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build iOS IPA
        run: |
          flutter build ipa --export-method development --no-codesign

      - name: Upload IPA file
        uses: actions/upload-artifact@v4
        with:
          name: TipMe-App-IPA
          path: build/ios/ipa/*.ipa
