name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --export-method development --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: App-IPA
          path: build/ios/ipa/*.ipa
